name: Task Flow

on:
  push:
    branches: ["**"]
    paths:
      - "project-2-task-flow/**"
      - ".github/workflows/project-2-task-flow.yml"
  pull_request:
    branches: ["**"]
    paths:
      - "project-2-task-flow/**"
      - ".github/workflows/project-2-task-flow.yml"

defaults:
  run:
    working-directory: project-2-task-flow

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "24"
          cache: "npm"
          cache-dependency-path: project-2-task-flow/package-lock.json
      - run: npm ci
      - run: npm run typecheck
      - run: npm run lint

  test:
    needs: build
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "24"
          cache: "npm"
          cache-dependency-path: project-2-task-flow/package-lock.json
      - run: npm ci
      - run: npm test

  gitleaks:
    needs: test
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  sonarqube:
    needs: gitleaks
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "24"
          cache: "npm"
          cache-dependency-path: project-2-task-flow/package-lock.json
      - run: npm ci
      - run: npm run build -w apps/api
      - run: npm run build -w apps/web
      - uses: sonarsource/sonarqube-scan-action@v5
        with:
           projectBaseDir: project-2-task-flow
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      
